name: ${project.name}
version: ${project.version}
description: ${project.description}
author: lokka30
website: www.lokka30.me
contributors: [lokka30, BtoBastian, Lori00]

main: me.lokka30.microlib.MicroLib
api-version: '1.13'
load: STARTUP

commands:
  microlib:
    description: View information about MicroLib, or manage the plugin.
    usage: /<command> [reload/backup]

permissions:
  microlib.*:
    description: Contains all MicroLib permissions.
    default: op
    children:
      microlib.reload: true
      microlib.backup: true
  microlib.reload:
    description: Allows the user to run /microlib reload.
    default: op
  microlib.backup:
    description: Allows the user to run /microlib backup.
    default: op