name: ${project.name}
version: ${project.version}
description: ${project.description}
author: lokka30
website: https://www.spigotmc.org
main: me.lokka30.microlib.MicroLib
load: STARTUP
api-version: '1.13'